schema_version = "1.0.0"
id = "Default_Setup_Addon" 
version = "2.0.0"
name = "Default Setup"
tagline = "An addon to help setup your scene."
maintainer = "That Random Blender Guy"
type = "add-on"
blender_version_min = "4.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
tags = ["User Interface","3D View"]

documentation = "https://github.com/That-Random-Guy567/Default-Setup-Addon/blob/main/readme.md"
repository = "https://github.com/That-Random-Guy567/Default-Setup-Addon.git"
issues = "https://github.com/That-Random-Guy567/Default-Setup-Addon/issues"
# website = "https://github.com/That-Random-Guy567/Default-Setup-Addon"

warning = "This addon is currently in Development. Not all features have been implemented yet."